clc; clear; close all;
bagName = '/home/doom/2011-01-21-09-01-36.bag';
bagselect = rosbag(bagName);
% /wide_stereo/left/image_rect
% /wide_stereo/left/camera_info
% /torso_lift_imu/data
% base_footprint
bagselect2 = select(bagselect, ...
                    'Time', ...
[bagselect.StartTime bagselect.EndTime], ...
                    'Topic', ...
                    '/torso_lift_imu/data');
startTime = bagselect.StartTime;
%%
fid = fopen('imu.txt', 'w+');
for i = 1:bagselect2.NumMessages
    msgs = readMessages(bagselect2,i);
    time_Sec = msgs{1}.Header.Stamp.Sec;
    time_nSec = msgs{1}.Header.Stamp.Nsec;
    time = str2double([num2str(time_Sec) '.' num2str(time_nSec)]);
    dt = time - startTime;
    
    omega = [msgs{1}.AngularVelocity.X;...
             msgs{1}.AngularVelocity.Y;...
             msgs{1}.AngularVelocity.Z];
    accel = [msgs{1}.LinearAcceleration.X;...
             msgs{1}.LinearAcceleration.Y;...
             msgs{1}.LinearAcceleration.Z];
    fprintf(fid, '%s %s %s %s %s %s %s\n', ...
            dt      , ...
            omega(1), ...
            omega(2), ...
            omega(3), ...
            accel(1), ...
            accel(2), ...
            accel(3));
    disp(['exporting bag file with process ' num2str(100*i/bagselect.NumMessages) '%\n']);
end